name: mytencloud_flupro
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.2.1
  flutter_staggered_grid_view: ^0.4.0
  pedantic: ^1.11.1
  cupertino_icons: ^1.0.2
  fluttertoast: any
  #  fluttertoast: ^7.1.8
  hive: ^2.2.3
  dio: ^5.0.2
  sensors_plus: any
#  sensors_plus: ^1.3.2
  url_launcher: ^6.0.20
  image_picker: ^1.0.4
  image_picker_web_redux: ^2.0.1
  share_plus: any
#  share_plus: ^7.2.1
  flutter_swiper_null_safety: ^1.0.2
  animations: ^2.0.2
  shared_preferences: ^2.0.8
  image: ^4.0.15
  like_button: ^2.0.4
  crop: ^0.5.2
  #  贪吃蛇
  overlay_support: ^2.0.1
  sqflite: any
  #  sqflite: ^2.0.0+4
  flutter_slidable: ^3.0.1
  webview_flutter: ^4.10.0
#  webview_flutter: ^3.0.4
  lottie: ^3.3.1
#  lottie: ^2.3.0
  flutter_screenutil: ^5.0.0+2
  flutter_zoom_drawer: ^3.0.3
  #  跑马灯
  marquee: any
  connectivity_plus: ^6.0.0
#  connectivity_plus: ^5.0.0
  pull_to_refresh: ^2.0.0
  table_calendar: ^3.0.3
  fl_chart: ^0.55.1
  permission_handler: ^11.0.1
  flutter_inappwebview: ^6.0.0
  badges: ^2.0.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
#  intl: ^0.18.1
#  image_gallery_saver: ^2.0.3
dev_dependencies:
  path_provider: ^2.0.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
    - assets/images/saving_tips/
    - assets/images/choice/
    - assets/lifes/
    - assets/newhead/
    - assets/json/
    - assets/images/diary/
  module:
    androidX: true
    androidPackage: com.example.mytencloud_flupro
    iosBundleIdentifier: com.example.mytencloudFlupro
